FROM maven:3.8.8-amazoncorretto-17 AS build

COPY . /opt/app/
WORKDIR /opt/app/

RUN mvn package -DskipTests

FROM eclipse-temurin:17-alpine
COPY --from=build /opt/app/target/bookCatalog-0.0.1-SNAPSHOT.jar /app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar", "api"]